# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "./public"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/js/analyse/**/*"
    - "!src/assets/js/lib/**/*"
    - "!src/assets/js/*"
    - "!src/assets/img/**/*"
    - "!src/assets/scss/**/*"
    - "!src/assets/scss"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
  #  - "node_modules/foundation-sites/scss"
  #  - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  cwaa:
    - "src/assets/js/cwaa.js"
  entries:
    - "src/assets/js/app.js"
    - "src/assets/js/eventregistration.js"
    - "src/assets/js/screenshots.js"
  # Paths to root assets
  rootAssets:
    - "src/root-assets/*"
  wellKnown:
    - "src/well-known/*"
  # Path to generated blog files residing in folders of type YYYY-MM-DD-TITLE
  blogOutputs: "src/pages/{de,en}/blog/*-*-*-*/"
  # Path to generated blog files residing in folders of type YYYY-MM-DD-TITLE
  blogScienceOutputs: "src/pages/{de,en}/science/*-*-*-*/"
    