name: Cypress Test Production
# This workflow runs the Cypress test suite on the production server
# https://coronawarn.app

on:
  workflow_dispatch:
  schedule:
    # Run daily at 9:00 UTC
    - cron: "0 9 * * *"

jobs:
  Cypress-Test-Production:
    runs-on: ubuntu-latest
    env:
      NO_COLOR: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: electron
          headless: true
          config: baseUrl=https://coronawarn.app
          # Only run tests in top level of integration directory
          spec: cypress/integration/*.js
