name: Deploy Website
# Test locally with act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04 -j prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["master"]
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "prod"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # if: "github.repository == 'corona-warn-app/cwa-website'"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install requirements
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          sudo apt-get install -y libnode-dev libssl-dev automake npm nodejs libpng-dev libjpeg-dev s3cmd

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'

      - name: npm install
        run: npm install

      - name: gulp build
        run: npm run build

      - name: keepalive.html
        run: echo "OK" > public/keepalive.html
      
      # https://github.com/s3tools/s3cmd/issues/643
      - name: Remove python3-magic due to s3cmd incompatibility
        run: sudo dpkg --remove --force-depends python3-magic
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: cwa-website
          path: ${{env.DOTNET_ROOT}}/public
          
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: cwa-website

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cwa-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_03FDC8296FD34A30A37D15B4D3359576 }}
          package: .
