name: Test Links
# This workflow executes a subset of Cypress tests
# concerning
# - external links
# - anchor links


on:
  workflow_dispatch:
  schedule:
      # Run every Monday at 03:15 UTC
    - cron: '15 3 * * 1'

jobs:

  test-links:
    runs-on: ubuntu-latest
    env:
      # See issue https://github.com/cypress-io/cypress/issues/25357
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Check external links
      uses: cypress-io/github-action@v5
      with:
        build: npm run build
        start: npm run start-server
        wait-on: http://localhost:8000
        spec: cypress/e2e/hybrid/check_links.cy.js
        browser: chrome

    - name: Check anchor links
      uses: cypress-io/github-action@v5
      if: always()
      with:
        install: false
        spec: cypress/e2e/check_anchor_links.cy.js
        browser: chrome

    - name: Save Cypress logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress_logs
        path: cypress/logs
        retention-days: 7
