name: Test Links
# This workflow executes a subset of Cypress tests
# concerning
# - anchor links
# - external links

on:
  workflow_dispatch:
  schedule:
      # Run every Monday at 03:15 UTC
    - cron: '15 3 * * 1'

jobs:

  test-links:
    runs-on: ubuntu-latest
    env:
      # See issue https://github.com/cypress-io/cypress/issues/25357
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Check anchor links
      uses: cypress-io/github-action@v5
      with:
        start: npm start
        wait-on: http://localhost:8000
        spec: cypress/e2e/check_anchor_links.cy.js
        browser: chrome

    - name: Check external links
      uses: cypress-io/github-action@v5
      with:
        install: false
        spec: cypress/e2e/hybrid/check_links.cy.js
        browser: chrome
